public with sharing class DeclineProjectHandler {
    
    /*@InvocableMethod(label='decline project')
    public static void declineProject(List<Project__c> lst){
        List<Id> projectIds=new List<Id>();
        Integer indexProjectPickList=0;
        for (Project__c item : lst) {
            projectIds.add(item.Id);
            item.Project_Status__c=
                PickListValueHandler.getPickListProjectStatus().get(indexProjectPickList);
        }


    }*/
}
